FROM node:18
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
RUN cnpm install express body-parser chatgpt crypto axios

COPY . .

EXPOSE 3000
CMD ["node", "index.js"]